# Generated by Django 5.2.8 on 2025-11-25 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0003_alter_commentaire_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
